language: node_js

node_js:
  - 8
  - 10
  - 12

on:
  branch:
    - master
    - dev

install:
  - npm install

script:
  - npm run test
  - npm run changelog
  # - npm run coverage

after_script:
  # - npm run coveralls
